sourmash-bio/sourmash_plugin_branchwater

README.md
doc/README.md
pyproject.toml
python/pyo3_branchwater/sourmash_plugin.py
src/lib.rs

This PR:
- fixes `pyproject.toml`
- uses `"` instead of `'` for CSV output, per standard
- adds reporting on number of threads being used
- adds better documentation

MRG: upgrade sourmash plugin

---

src/lib.rs
src/python/pyo3_branchwater/__init__.py

default is `0` = full cpu (it considers the case it's running on a limited memory slurm job)

[MRG] Add `-c` `--cores`

---

LICENSE.txt
README.md
pyproject.toml
src/lib.rs
src/python/pyo3_branchwater/__init__.py
src/python/tests/test_mastiffsearch.py
src/python/tests/test_search.py

MRG: fix `if let` warnings

---

src/lib.rs
src/python/tests/test_search.py

Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/71

MRG: remove Jaccard calculation from manysearch

---

Cargo.toml
LICENSE.txt
README.md
pyproject.toml
src/lib.rs
src/main.rs
src/manysearch.rs
src/python/pyo3_branchwater/__init__.py
src/python/tests/test_search.py

NOTE: PR into #64.
This PR produces a `manysearch` CLI bin that can be used for profiling.

EXP: provide `manysearch` binary.

---

doc/README.md
src/lib.rs
src/python/pyo3_branchwater/__init__.py

This PR refactors the Rust code to report details of errors when loading sketches.
Also does some minor cleanup and disambiguation of the docs and Python plugin.

MRG: report load sketch errors

---

src/check.rs
src/fastgather.rs
src/fastmultigather.rs
src/index.rs
src/lib.rs
src/manysearch.rs
src/manysketch.rs
src/mastiff_manygather.rs
src/mastiff_manysearch.rs
src/multisearch.rs
src/utils.rs

Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/62.
Supersedes #64
Supersedes https://github.com/sourmash-bio/pyo3_branchwater/pull/100

MRG: break up `lib.rs` into many different files

---

Cargo.lock
Cargo.toml
README.md
doc/README.md
src/README.md

@bluegenes should confirm this is how things work 😆 
Includes new behavior since 0.7.1, in PRs #99 and #105, and soon #106.
This also bumps pyo3_branchwater version to 0.8.0.
Breakdown of PRs is here: https://github.com/sourmash-bio/pyo3_branchwater/issues/108

RELEASE: update docs for new zipfile support!

---

.github/dependabot.yml

MRG: add dependabot config

---

src/manysketch.rs
src/python/tests/test_sketch.py

- fix reporting bug
- bail if no signatures created b/c all fastas are incompatible (e.g. dna fasta, protein sketch params)

MRG: fix reporting bug introduced in #123

---

src/utils.rs

MRG: fix error for large manysketch zips (> 4G)

---

pyproject.toml

mirror changes from https://github.com/sourmash-bio/sourmash/pull/2879
ref https://github.com/conda-forge/sourmash_plugin_branchwater-feedstock/pull/3

MRG: update MacOS builds in support of conda-forge releases.

---

src/utils.rs

https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/211 left an errant eprintln in that is ...challenging when loading large manifests 😆

MRG: remove eprintln from manifest loading

---

Cargo.lock
Cargo.toml

waiting for conda-forge etc to finish to make sure no more changes are needed in v0.9.0!

MRG: bump to v0.9.1-dev

---

src/fastmultigather.rs
src/manysearch.rs
src/mastiff_manysearch.rs
src/multisearch.rs
src/pairwise.rs

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/171

MRG: avoid printing out 0s

---

src/utils.rs

**Note:** PR into https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318

MRG: Adjust denominator of `f_unique_to_query` in #298

---

src/fastgather.rs
src/fastmultigather.rs
src/lib.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/utils.rs

NOTE: PR into https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/298
Removes `--full-results` and updates tests for switch to full results by default.

WIP: Remove minimal results option

---

src/pairwise.rs
src/python/sourmash_plugin_branchwater/__init__.py

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/357

MRG: write self comparisons for all sketches with `--write-all`

---

src/fastmultigather.rs
src/lib.rs

Note: PR into #397
This PR makes a few minor adjustments to #397.

MRG: update `--save-matches` code a bit.

---

doc/README.md

MRG: documentation updates based on new collection loading

---

.gitignore
doc/developer.md
pixi.lock
pyproject.toml

- Set up pixi configs in `pyproject.toml`, mirroring the ones from sourmash
- Add dev docs on how to use pixi
Not sure if replace or keep as separate section in docs...

Set up pixi for development environment

---

src/multisearch.rs
src/search_significance.rs

@olgabot speak now or forever hold your peace ;)

MRG: fix a variety of small clippy issues

---

Cargo.lock
Cargo.toml
src/fastmultigather.rs
src/fastmultigather_rocksdb.rs
src/index.rs
src/manysearch.rs
src/manysearch_rocksdb.rs
src/multisearch.rs
src/pairwise.rs
src/python/tests/sourmash_tst_utils.py
src/python/tests/test_fastmultigather.py
src/python/tests/test_index.py
src/utils/mod.rs
src/utils/multicollection.rs

Update plugin with fix in https://github.com/sourmash-bio/sourmash/pull/3387, as well as https://github.com/sourmash-bio/sourmash/pull/3397.
NOTE: this needs to wait for the next sourmash release after r0.17.1 - presumably r0.17.2.
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/513
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/519
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/505

MRG: update code after sourmash fix to `Collection::sig_from_record()`

---

Cargo.lock
src/lib.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_sketch.py
src/singlesketch.rs

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/462

MRG: add `--input-moltype` to singlesketch

---

src/python/tests/sourmash_tst_utils.py

https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/546, but into main, since other PRs are now failing ;)

MRG: switch to `importlib.metadata` from `pkg_resources` (into main)

---

README.md

realized I previously added logo to the doc README; this PR adds the same logo to the main README

MRG: add logo to main readme

---

pyproject.toml

MRG: fix `pyproject.toml` version to 0.9.14-dev

---

Cargo.lock
Cargo.toml

zip 2.3.1 had the bug, so they must have meant it was fixed in v2.5. Seems to work now for me!
- fixes #389

MRG: update zip version to 2.5
