Cargo.lock
src/lib.rs
src/python/tests/test_gather.py

Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/41
(This was actually fixed in https://github.com/sourmash-bio/pyo3_branchwater/pull/32 and released in 0.5.0 I think, but this adds better reporting :))

MRG: add more output information when sketches fail to load

---

src/python/pyo3_branchwater/__init__.py

this mimics default parameters for sourmash.
Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/42

MRG: adjust default threshold-bp to 50kb for fastgather and fastmultigather

---

Cargo.lock
Cargo.toml
src/lib.rs
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/python/tests/test_search.py

This PR refactors `prepare_query` to incorporate common code, and also outputs the original md5sum for matches, not the downsampled one.
Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/30
Bumps version to 0.6.0
TODO:

MRG: report correct md5sum

---

src/lib.rs
src/python/tests/test_gather.py
src/python/tests/test_multigather.py

Fixes https://github.com/sourmash-bio/pyo3_branchwater/issues/46
The contents themselves may differ a bit - for example, here we use full md5sum as opposed to short md5sum in sourmash output - but that's an issue for another day.

MRG: adjust column names to match sourmash prefetch

---

LICENSE.txt
README.md
pyproject.toml

as discussed on slack and in https://github.com/sourmash-bio/pyo3_branchwater/issues/60, we are switching the license over to AGPL from BSD.

MRG: switch to AGPL license

---

Cargo.lock
Cargo.toml
src/python/tests/__init__.py
src/python/tests/conftest.py
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/python/tests/test_search.py

This PR updates the tests so that the number of threads is set once per test run.
Explanation:
* in #57 we started using `pyo3_branchwater.set_global_thread_pool` to set the threads per user request on `-c/--cores`
* `set_global_thread_pool` can only set the number of threads once!
* in #65 I added a command line test of `sourmash scripts manysearch -c 4`
* however, if that new test wasn't the first test run, then whichever test _was_ run first would set the threads to the default, which is the max cores available
* this would then cause the new test to fail
Specifically, on my laptop, the number of cores would always get set to 8. No bueno!
This PR adds a call on test import to `set_global_thread_pool(4)`, which matches the number used in `test_search.py::test_simple_with_cores`. And the …

MRG: set num threads once per test run

---

Cargo.toml
src/lib.rs
src/python/pyo3_branchwater/__init__.py

If I'm not mistaken, we can't yet robustly read signatures from sig `zip` files into rust. This is an experimental hackaround to extract files from zip and then pass the new filepaths into the branchwater/mastiff `index` function.
chatgpt helped me a lot with the rust, so I make no guarantees on it ... just that it seems to work for me.
indexing gtdb:
```
time sourmash scripts index gtdb-rs214-reps.k31.zip -o gtdb-rs214-reps.k31.rdb
== This is sourmash version 4.8.3. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==
ksize: 31 / scaled: 1000 / threshold: 0.01
indexing all sketches in 'gtdb-rs214-reps.k31.zip'
wrote 85205 signatures to temp dir
Loaded 85205 sig paths in siglist
...index is done! results in 'gtdb-rs214-reps.k31.rdb'
real    39m56.399s
user    33m57.385s …
```

[MRG] allow index from a signature zipfile

---

src/lib.rs
src/python/pyo3_branchwater/__init__.py

Since we reuse the multithreading code in each function (and I wanted to understand it better), this PR abstracts the writer thread into a reusable function and uses it in both `manysearch` and `mastiff_manysearch`.
Ideally, we could reuse this for all functions (gather, etc) -- but, I wanted a review to see if this went in the right direction.
Since this change means that we need to pass a consistent object to the writer, this PR also creates a `SearchResult` struct (and associated methods) that is created during each 'search' loop and passed to the writer thread. 
For gather (a later PR if we want to go this route), Luiz already has a GatherResult in the works (https://github.com/sourmash-bio/sourmash/blob/ba581ea8c6f046b7e19da274155f326d2bdbc8e7/src/core/src/index/revindex.rs#L572), so …

[MRG] abstract writer thread into reusable function

---

src/lib.rs
src/python/tests/test_index.py

The info lines weren't reporting by default.

MRG: replace `info` with `eprintln`

---

doc/README.md
src/lib.rs
src/python/pyo3_branchwater/__init__.py

Fixes #67 
contains leftovers from https://github.com/sourmash-bio/pyo3_branchwater/pull/89 too.

MRG: rename rust functions to match CLI.

---

src/index.rs
src/manysketch.rs
src/multisearch.rs
src/python/tests/test_index.py
src/python/tests/test_multisearch.py
src/utils.rs

Extracted from #99, because all the changes were getting unruly.
This should be easier to review - contains the functions & modifications to use them in `index` and `multisearch`, with tests.
New in `utils.py`:
- load_sigpaths_from_zip_or_pathlist
- load_sketches_from_zip_or_pathlist
- report_on_sketch_loading (unifies signature loading reporting)
Renamed:
- `read_signatures_from_zip` --> `load_sketches_from_zip`
- `load_sketch_fromfile` --> `load_fasta_fromfile`
Note: In the case of reading a pathlist from a zip file, this means we extract the sig files and store them in a temp directory which will be deleted when it goes out of scope. This adds a little overhead, but I think it could worth it for the simplicity of being able to specify a zip database. Open to removing, though.

MRG: add utility functions for zip reading; use in index, multisearch

---

src/fastgather.rs
src/python/tests/test_gather.py
src/python/tests/test_multigather.py

Follow up to #105: 
- Enables sourmash zipfiles to be used as database input for `fastgather`.
to do:
- we're not using the reporting (b/c different loading), but I unified the output phrasing in anticipation of better zip loading in the future (see note).
Note: To keep this simple, I was just planning on adding suboptimal zip loading, as `fastgather` loads database signatures using a sketch template and `threshold` parameter, which we don't have in the zip loading function. 
These could/should be added to allow directing loading of signatures from the zipfile (as suggested in #113).
Closes #108

MRG: add zip loading for `fastgather`

---

.github/workflows/build-test.yml
src/check.rs
src/fastgather.rs
src/fastmultigather.rs
src/index.rs
src/lib.rs
src/manysearch.rs
src/manysketch.rs
src/mastiff_manygather.rs
src/mastiff_manysearch.rs
src/multisearch.rs
src/utils.rs

Applied [rustfmt](https://github.com/rust-lang/rustfmt) to the entire Rust codebase with `cargo fmt --all` per https://github.com/sourmash-bio/pyo3_branchwater/issues/103

MRG: run `cargo fmt --all` on the entire codebase

---

src/manysketch.rs

For a small csv file (especially with large files), the prior printout was misleading. After opening one file per thread, the message claims x% done. In reality, we've just opened the files to start building sketches.

MRG: clearer message for manysketch

---

src/manysketch.rs

Previously, `manysketch` was reading entire fasta files into memory. 
I always intended to iterate, I just lost track of it.
Revealed by #122

MRG: actually iterate through reads

---

Cargo.lock
Cargo.toml
src/fastgather.rs
src/manysketch.rs
src/mastiff_manysearch.rs

This PR cleans up several clippy suggestions, and also bumps the version to v0.8.1.

MRG: fix clippy stuff; bump to v0.8.1

---

src/fastgather.rs
src/fastmultigather.rs
src/index.rs
src/manysearch.rs
src/mastiff_manygather.rs
src/mastiff_manysearch.rs
src/python/tests/test_index.py
src/utils.rs

- Improves sigpath loading from zips by checking for compatibility with desired sketch parameters first.
- Allows `sourmash scripts index` with a multi-parameter zipfile.
Fixes #109
Fixes #113

MRG: only load zip paths with compatible sketches

---

src/mastiff_manygather.rs
src/python/tests/test_index.py
src/utils.rs

as noted in https://github.com/sourmash-bio/sourmash/issues/2749#issuecomment-1715762525, sourmash zipfiles store repeated md5sums as `.sig.gz_{n}` instead of `_{n}.sig.gz`. This PR allows us to read those files as well, rather than skipping over them.

MRG: read `sig.gz_{n}` sigs from zipfiles

---

environment.yml

As mentioned here : https://github.com/sourmash-bio/pyo3_branchwater/issues/148, added `compilers` to the `environment.yml` file which then resulted in a successful installation of `branchwater`!
```
(branchwater-dev)
✘  ♥ 93%  Mon 13 Nov - 11:11  ~/code/pyo3_branchwater   origin ☊ main ↓2 1☀ 1● 
@olgabot  mamb env create --file environment.yml --name branchwater-dev-v2
zsh: correct 'mamb' to 'mamba' [nyae]? y
conda-forge/osx-64                                          Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-64                                             Using cache
bioconda/noarch                                             Using cache
pkgs/main/osx-64                                              No change
pkgs/main/noarch …
```

Add "compilers" to environment.yml

---

pyproject.toml
src/lib.rs
src/pairwise.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_pairwise.py

This pull request introduces a new command called `pairwise`. It is similar to the existing `multisearch` command, but it uses half the memory, time, and disk space by avoiding self and bidirectional comparisons. 
usage is similar to `multisearch` except for a single positional argument of sig paths file instead of query and target.
---
```bash
sourmash scripts multisearch sig_paths.l sig_paths.l  -c 16 -k 51 -s 10000 -o multisearch_result.csv
sourmash scripts pairwise sig_paths.l  -c 16 -k 51 -s 10000 -o pairwise_result.csv -t 0.0
```
```python
import pandas as pd
import numpy as np
df_multisearch = pd.read_csv('multisearch_result.csv')
df_pairwise = pd.read_csv('pairwise_result.csv')
multisearch_unique_query_name = set(df_multisearch['query_name'].unique())
assert len(df_pairwise) == …
```

MRG: Add the `pairwise` subcommand

---

src/python/tests/test_gather.py
src/utils.rs

This PR updates `collection_from_pathlist` to first load the list of paths, and then load them all in parallel; previously, in #211, the sketches were all loaded in serial, resulting in an 18x fold slowdown vs other methods.
Benchmark proof: https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/214#issuecomment-1950646175
It also fixes a test to write manifests to the temp directory rather than the `test-data` directory.
Fixes #220

MRG: parallelize `collection_from_pathlist`

---

src/python/tests/test_sketch.py
src/utils.rs

In sourmash, protein k-mer sizes are k=k*3 internally, but manifest ksizes are just k. 
So we need to remember to do some conversions :)
In the python manifest-making code, `minhash.ksize()` does the conversion back for us, so we ignore. In rust, `sketch.ksize()` does not convert back for us, so when we go to get k-mer sizes for the manifest, we need to convert back (k/3) to get the original ksize.
Fixes #216

MRG: fix manifest protein k-mer sizes

---

Cargo.lock
Cargo.toml
doc/README.md
src/utils.rs

After https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/197 and https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/211, we need to switch up our documentation and references for using the branchwater plugin.
This PR also adds documentation for `pairwise` and suggests `.rocksdb` as the suffix for `index` output.
Finally, this PR bumps the version to v0.9.0 in preparation for a release. 🎉 
The updated `doc/README.md` is [here](https://github.com/sourmash-bio/sourmash_plugin_branchwater/blob/update_docs2/doc/README.md).
HackMD version of `doc/README.md` for nicer viewing/editing: https://hackmd.io/_DqWfa8BS364lfjhnvfnOg?view
- Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/212
- Fixes …

MRG: update docs for v0.9.0

---

Cargo.lock
Cargo.toml
src/check.rs
src/fastgather.rs
src/lib.rs
src/manysketch.rs
src/mastiff_manygather.rs
src/mastiff_manysearch.rs
src/python/tests/test_gather.py
src/python/tests/test_sketch.py
src/utils.rs

This PR updates manifest generation in `manysketch` to use `Record` and `Manifest` utils from core. This also makes the code significantly simpler, since we can generate manifest information directly from the signature, rather than saving sketch parameters alongside sketches. 
Required `0.13.0` core due to these fixes:
- https://github.com/sourmash-bio/sourmash/pull/3007
- https://github.com/sourmash-bio/sourmash/pull/3019
* Fixes #203

MRG: Use `core` manifest utils

---

src/lib.rs
src/multisearch.rs
src/pairwise.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_multisearch.py
src/python/tests/test_pairwise.py
src/utils.rs

Adds ANI columns to pairwise and multisearch output, building off of @mr-eyes's ANI translations (#188) which got streamlined + added into sourmash core in https://github.com/sourmash-bio/sourmash/pull/2943
Split from #234 to make things more concise/simpler.
79.8m comparisons
| version | experiment | time |
| -------- | -------- | -------- |
| PR | no ANI     | 21s     | 
| PR | with ANI     | 20s     |
| v0.9.0 | no ANI | 21s |
79.8m comparisons
| version | experiment | time |
| -------- | -------- | -------- |
| PR | no ANI     | 14m 0s     | 
| PR | with ANI     | 14m 6s     | 
| main branch (~v0.9.0) | no ANI | 14m 47s |

MRG: Add ANI output to `pairwise`, `multisearch`

---

src/python/sourmash_plugin_branchwater/__init__.py

Note: PR into https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/234
This PR fixes a few nits:
* the default argument to `--similarity-column` was a no-longer-valid column name
* the help string for `--threshold` contained an unescaped `%` causing argparse to fail on `-h`
* indents and spacing were adjusted
Ready for merge @bluegenes!

MRG: fix argparse stuff in `cluster` command

---

doc/README.md
src/lib.rs
src/manysketch.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_sketch.py
src/utils.rs

Here I modify `manysketch` to allow:
- sketching multiple input files into the same sketch
- sketching singletons!
New Functions
- `detect_csv_type` - figure out which type of acceptable input csv we have
- `process_assembly_csv` - process standard `fromfile` csv (headers: `name,genome_filename,protein_filename`). This was originally part of `load_fasta_fromfile`.
- `process_reads_csv` - process new `reads` csv (headers: `name,read1,read2`)
This refactoring also makes it much simpler for us to add new types of CSVs that can be read.
Notes:
- parallelization is still done by each set of inputs that should yield signatures. If singleton, we're sketching all records for a given file in series, not all sketches in parallel.
- perhaps a confusing thing: when sketching with `--singleton`, the …

MRG: enable `singleton` sketching, facilitate `reads`-based sketching

---

src/manysketch.rs
src/mastiff_manygather.rs
src/utils.rs

Forgot to consult our clippy overlord for that PR :). 
Here, we use FastaData struct to reduce return complexity from fasta csv reading.

MRG: fix clippy warnings from `manysketch` improvements

---

Cargo.lock
Cargo.toml

release notes - [edit](https://hackmd.io/fdjNJ7BxQ32v_2Gel9Lp3Q?both)
Updates and features:
* Add graph-based clustering with `cluster` (#234)
* Enable `singleton` sketching, facilitate `reads`-based sketching in `manysketch` (#184)
* Use updated core `GatherResult` to enable full results from `fastmultigather`(#205)
* Add ANI output to `pairwise`, `multisearch` (#236)
* Use `core` manifest utils (#217)
* Fix clippy warnings from `manysketch` improvements (#251)
Dependency updates:
* Bump conda-incubator/setup-miniconda from 3.0.1 to 3.0.2 (#242)
* Bump env_logger from 0.10.2 to 0.11.2 (#240)
* Bump pyo3 from 0.20.2 to 0.20.3 (#241)
* bump to v0.9.1-dev (#230)
* Bump anyhow from 1.0.79 to 1.0.80 (#227)
* Bump assert_cmd from 2.0.13 to 2.0.14 (#229)

MRG: PR to release v0.9.1

---

src/manysearch.rs
src/mastiff_manysearch.rs
src/python/tests/test_search.py
src/utils.rs

- adds `query_containment_ani`, `match_containment_ani`, `average_containment_ani`, `max_containment_ani` to `manysearch`
- just adds `query_containment_ani` to rocksdb `manysearch`, since we don't have access to target sig for other calculations.

MRG: add ANI to manysearch

---

src/index.rs
src/python/tests/test_index.py

`index` has been failing silently if there are no signatures to index by producing a rocksdb database that is just empty of sigs. It's been quite frustrating with issues arising from protein databases with pre-0.9.0 (aka incorrect) manifests :).
This PR changes `index` to Error out if there are no sigs to index.
I thought this had been handled as per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/207, but regardless, it is fixed here.

MRG: index should error out if no sigs to index

---

src/manysketch.rs
src/python/tests/test_sketch.py

- fixes #282
This bug caused sketch names to be set only for the first sketch for a given file, and _not_ set for any additional sketches. This means, if we were sketching at `k=21,k=31,k=51`, only the `k=21` sketches would have the name properly set.

MRG: fix manysketch naming bug

---

src/index.rs
src/python/tests/test_multigather.py
src/python/tests/test_multisearch.py
src/python/tests/test_search.py
src/utils.rs

Error out when 0 signatures are loaded from a collection. 
Since we currently only load a single collection as our query or database, 0 sigs in either means that no useful results would be obtained.
- Fixes #207

MRG: fail-exit when 0 signatures are loaded from a collection

---

Cargo.lock
Cargo.toml

* MRG: bump version to v0.9.3-dev by @ctb in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/278
* MRG: fix manysketch naming bug by @bluegenes in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/284
* MRG: fail-exit when 0 signatures are loaded from a collection by @bluegenes in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/282
**Full Changelog**: https://github.com/sourmash-bio/sourmash_plugin_branchwater/compare/v0.9.2...v0.9.3

MRG: bump version to 0.9.3

---

src/utils.rs

+1 - faster loading
-1 - likely does not preserve ordering?
ref #268 
HG38 entire vs GTDB rs214 @ k=51
| code | Walltime | % CPU | RAM/RSS |
| -------- | -------- | -------- | -- |
| v0.9.3 | 50m 47s     | 100% | 24.5 GB |
| this PR |  30m 38s     | 213% | 24.7 GB |

MRG: parallelize loading sketches into memory

---

Cargo.lock
Cargo.toml
src/fastmultigather.rs
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/utils.rs

fixes #303 
Actually, we didn't need https://github.com/sourmash-bio/sourmash/pull/3121 after all. I didn't realize that `Record.filename` is the originating FASTA filename, not the signature location. To match sourmash gather output, we just need the `location`/`internal_location`.

fill out `match_filename` in the non-rocksdb full-result gathers

---

.github/workflows/build-test.yml
src/lib.rs
src/mastiff_manygather.rs
src/python/tests/test_multigather.py
src/utils.rs

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/313
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/285
Addresses #239 / #299 by bailing out when an output path is provided but will not be used:
```
RuntimeError: output path specified, but not running fastmultigather against a rocksdb. See 
issue #239
```
although we are leaning towards respecting `-o` in the future, see #299 discussion, so this will soon get revisited.

MRG: fix lint error, & processed sig reporting for rocksdb/fastmultigather

---

.github/workflows/build-test.yml
Cargo.toml

Fix broken CI. Among other things,`actions-rs` is unmaintained per https://github.com/actions-rs/toolchain/issues/216. I think the original breakage might have been occasioned by the runner image for ubuntu-latest being updated about two weeks ago ([link](https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md)).
A laundry list of problems to fix seems to have boiled down to:
* don't mix rustup installs with conda installs;
* if you're going to use conda-incubator/setup-miniconda, do not set `use-only-tar-bz2` to true (https://github.com/conda-incubator/setup-miniconda/issues/267#issuecomment-2102569634)
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/321

MRG: fix CI build & tests

---

Cargo.lock
Cargo.toml
src/fastgather.rs
src/fastmultigather.rs
src/lib.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/utils.rs

This PR adds utilities for building full gather results file for `fastgather` and non-rocksdb `fastmultigather`, and makes full output default.
- Fixes #287 
- Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/187
- Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/254
- includes a local fix for https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/318, which means that the `fastgather` and **non-rocksdb** `fastmultigather` full output here matches sourmash gather. Issues with rocksdb gather are being handled elsewhere.
| software/version | command | details | time | max RAM |
| -------- | -------- | -------- | -- | -- |
| branchwater v0.9.3 | `fastgather` | minimal result | <span style="color:green">**1m 47s**</span> | <span …

MRG: write full gather result from `fastgather` and non-rocksdb `fastmultigather`

---

Cargo.lock
Cargo.toml
pyproject.toml
src/python/tests/test_multigather.py

In https://github.com/sourmash-bio/sourmash/pull/3193, we fixed the RocksDB-based gather problem described in #322.
Now that https://github.com/sourmash-bio/sourmash/pull/3193 is merged, we need to:
* Fixes #322.

WIP: fixed RocksDB-based `fastmultigather`

---

src/manysketch.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_sketch.py
src/utils.rs

- fixes `dayhoff`, `hp` param parsing and sig template building
- based on changes in https://github.com/sourmash-bio/sourmash_plugin_directsketch/pull/55
- also adds some checks for moltype, ksizes in param str, since those are not set by default in the `parse_param_str` function.

MRG: add `dayhoff`/`hp` sketching improvements from `directsketch`

---

src/python/tests/test_pairwise.py
src/utils.rs

I noticed a strange output when running `pairwise`:
```
Loaded 1000 signature signature(s)
```
I was curious about the redundancy and tracked this down to ReportType => string formatting.
I think having this be:
Loaded 1000 analysis signature(s)
makes a bit more sense.
Small change, but 🤷 :)

MRG: update ReportType string output

---

src/utils.rs

ref:
- #330 
- #331
With fixed `query_bp` and `query_n_hashes`, this should work with `sourmash tax`

MRG: fix fastgather `query_bp` and `query_n_hashes` to restore tax compatibility

---

Cargo.lock
Cargo.toml
src/python/tests/test_gather.py
src/python/tests/test_multigather.py
src/utils.rs

Calculate ANI of matches against original query with `f_orig_query` and `f_match_orig`, instead of against `f_unique_to_query` and `f_match`.
This fixes the ANI differences between `sourmash gather` and non-RocksDB branchwater gather for the columns `query_containment_ani`, `match_containment_ani`, `max_containment_ani`, and `average_containment_ani`.
This also brings in the sourmash core working branch https://github.com/sourmash-bio/sourmash/pull/3218 which fixes the RocksDB-based numbers.
Fixes #331 🎉

MRG: fix ANI from non-rocksdb gather output

---

Cargo.toml
README.md
doc/README.md
src/python/sourmash_plugin_branchwater/__init__.py

This PR follows #360 and #361, which fix the gather output to be ~100% sourmash compatible.
This PR:
* updates docs around gather per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/329
* mentions betterplot plugin per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/350
* fixes `-h/--help` messages
* removes manifest CSV recommendations for now because of #266/#347;
* bumps version to v0.9.5 🎉 
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/329
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/350
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/362

MRG: update docs and `-h` messages for v0.9.5 release

---

.github/dependabot.yml
Cargo.lock
Cargo.toml
src/manysketch.rs
src/utils.rs

Required changes for zip crate:
- update zip from 0.6 to 2.0 (NOT 2.3.1, as 2.1+ have a bug for large files)
- change `FileOptions` to reflect altered structure in 2.x
Simplifications:
- simplify zip writing to remove Arc and ZipMessage
> previously, we needed to keep track of additional information for all signatures in order to be able to write the manifest. Upon switching to sourmash core's manifest writing (#217), we no longer need to keep track of all signature information and remove this overly complicated implementation.

MRG: update zip crate to 2.0

---

src/lib.rs

Fix this warning:
```
warning: use of deprecated method `pyo3::deprecations::GilRefs::<T>::function_arg`: use `&Bound<'_, T>` instead for this function argument
--> src/lib.rs:310:45
|
310 | fn sourmash_plugin_branchwater(_py: Python, m: &PyModule) -> PyResult<(...
|                                             ^
|
= note: `#[warn(deprecated)]` on by default
```
by swiping code from directsketch.
Note, it looks to me like this will make the pyo3 version bump in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/382 work as well 🎉

MRG: fix deprecated method warning in `lib.rs`

---

src/mastiff_manygather.rs
src/python/tests/test_multigather.py

This fixes an issue noted in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/390#issuecomment-2225942342, where if a RocksDB cannot load a sketch from external FSStorage, `fastmultigather` outputs an error message, but doesn't actually error exit.
With this PR, a clear error message is printed. However, we don't quit out of the fastmultigather early; that seemed like a harder fix :).

MRG: add error-exit in fastmultigather against rocksdb for failed gather

---

src/manysearch.rs
src/mastiff_manysearch.rs
src/python/tests/test_search.py
src/utils.rs

Addresses https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/380
Note: in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/302, the meaning of 'query' and 'against' was flipped. For `manysearch`, unlike in `gather`/`prefetch`, 'query' is meant to be the genome and `against` is meant to be the metagenome. This PR switches them back, so that the `mgmanysearch` command line from [the containment search plugin](https://github.com/sourmash-bio/sourmash_plugin_containment_search/) matches the `manysearch` command line:
```
sourmash scripts mgmanysearch --queries f_prausnitzii.sig.zip b_uniformis.sig.zip --against CD*.sig.zip -o search.csv
```
vs
```
sourmash scripts manysearch query.txt against.txt -o search2.csv -t 0
```
where `query.txt` contains …

MRG: add additional weighted information to `manysearch` output

---

src/python/tests/test_multigather.py

PR into #397
- use built in cwd setting
- do a more explicit test of expectations for saved matches

MRG: more updates for `--save-matches`

---

src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/conftest.py
src/python/tests/sourmash_tst_utils.py
src/python/tests/test_cluster.py
src/python/tests/test_fastgather.py
src/python/tests/test_fastmultigather.py
src/python/tests/test_index.py
src/python/tests/test_manysearch.py
src/python/tests/test_multisearch.py
src/python/tests/test_pairwise.py
src/utils.rs

Cleanup:
- make moltype "DNA" instead of "dna" to match sourmash
Refactoring:
- consolidate duplicate test functions
- move common parametrize marks from pytest into `conftest.py`
- rename `test_gather.py` to `test_fastgather.py`
- rename `test_multigather.py` to `test_fastmultigather.py`

MRG: misc cleanup

---

src/fastmultigather.rs
src/lib.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_fastmultigather.py

In-memory `fastmultigather` currently only creates output files (`*.gather.csv`, `*.prefetch.csv` if matches are found. Here, we add an option `--create-empty-results` (already a standard `sourmash gather` option; added in https://github.com/sourmash-bio/sourmash/pull/2557 ) to touch the empty files. This is primarily useful for snakemake workflows, we often need all output files to be created for use in downstream steps.
Note: **this only creates empty files if we would expect results (i.e. matching sketch parameters but just no overlapping hashes).** We could also create empty files for sketches without matching params, but that was unnecessary for my application and seemed excessive to me. Happy to add if there's a good reason.
When running `sourmash tax` on empty gather files, we can …

MRG: optionally, create empty results files for in-memory `fastmultigather`

---

Makefile

This prevents `make` from recognizing directories as satisfying the target.

MRG: add .PHONY targets to Makefile

---

src/index.rs
src/python/tests/test_fastgather.py
src/python/tests/test_fastmultigather.py
src/python/tests/test_index.py
src/utils/multicollection.rs

NOTE: PR into #450
This PR adjust `MultiCollection` to load sketches into memory if internal storage is specified, which allows `index` to index anything loadable by `MultiCollection` as long as it fits into memory.
ref @olgabot request [here](https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/354#issuecomment-2336402747)
TODO:

MRG: clean up index to use `MultiCollection`

---

src/index.rs
src/python/tests/test_fastgather.py
src/python/tests/test_fastmultigather.py
src/python/tests/test_index.py
src/python/tests/test_multisearch.py
src/utils/multicollection.rs

NOTE: PR into https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/430
Includes https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/451
This PR adjusts `MultiCollection::load_set_of_paths` to return a `MultiCollection` itself, so that we can do recursive loading of multi-collections from within multi-collections, e.g. manifests from within pathlists (and maybe vice versa?). It also includes modifications from #450 that let `index` use anything loadable from `MultiCollection` with internal storage, by loading it into memory and then saving it internally.
Also adds a few tests.
The code ends up being ~simpler too, which is nice.

MRG: support & test loading of standalone manifests within pathlists

---

README.md
doc/README.md
pyproject.toml
src/lib.rs
src/manysketch.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_sketch.py
src/singlesketch.rs
src/utils.rs

This PR adds the `singlesketch` command to directly sketch a FASTA or stdin to resemble the regular `sourmash sketch` command.

Add `singlesketch` command

---

src/lib.rs
src/manysearch.rs
src/python/sourmash_plugin_branchwater/__init__.py

Tackles https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/463
This PR adjusts `manysearch` so that downsampling is only done on sketches when actually needed. Prior to this, the `downsample_max_hash/downsample_scaled` code was running on sketches even when there was no need.
This PR also adds `--ignore-abundance` to `manysearch` which optionally turns off potentially expensive abundance estimation (which in practice is not that expensive, apparently; see #463).
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/466

MRG: fix performance regression in `manysearch` by removing unnecessary downsampling

---

.github/workflows/build-test.yml
Cargo.lock
Cargo.toml
src/manysearch.rs
src/python/tests/test_fastmultigather.py
src/utils.rs

This PR is a standing PR to update to the forthcoming sourmash release, probably 0.16.0, which will hopefully include:
- https://github.com/sourmash-bio/sourmash/pull/3344 (not projected to cause any problems ;)
- and (hopefully) https://github.com/sourmash-bio/sourmash/pull/3342 (will need changes here ;))
Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/468
TODO:

MRG: update to code for forthcoming sourmash release

---

src/python/tests/sourmash_tst_utils.py

pkg_resources is now deprecated (and in some situations removed), so we should use importlib.metadata instead!

MRG: switch to `importlib.metadata` from `pkg_resources`

---

Cargo.lock
doc/README.md
src/lib.rs
src/manysearch.rs
src/manysearch_rocksdb.rs
src/multisearch.rs
src/pairwise.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_manysearch.py
src/python/tests/test_multisearch.py
src/python/tests/test_pairwise.py
src/utils/mod.rs

This PR adds `-A/--output-all-comparisons` to manysearch, multisearch, and pairwise. Updates documentation, adds tests, etc.
A few notes:
* `-t/--threshold` is ignored when `-A` is provided.
* manysearch against RocksDB will only output comparisons with some overlap; this is documented.
This PR also:
- adds a note about (lack of) semantic versioning, ref https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/539;
- advises using column names to parse CSV files, ref https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/539;
- removes many of the old version comments ("as of v0.9.whatever, ...") from the documentation;
- checks for directories as input and fails appropriately, per https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/533
Fixes …

MRG: add `--output-all-comparisons` to manysearch, multisearch, and pairwise

---

Cargo.lock
Cargo.toml
src/python/tests/test_fastgather.py
src/python/tests/test_fastmultigather.py
src/python/tests/test_index.py
src/python/tests/test_manysearch.py
src/python/tests/test_multisearch.py
src/python/tests/test_pairwise.py

This PR updates to sourmash core latest, which will be r0.18.0.
The biggest set of changes in the plugin relate to https://github.com/sourmash-bio/sourmash/pull/3431, which made it possible to detect bad (and good) zip files based on content, and handle the error; in particular, this means that we can continue past errors from reading a file misnamed as a sig zip file, and try reading it in other ways. So a bunch of tests (e.g. `test_fastgather.py::test_bad_against_3`) no longer apply!
sourmash r0.18.0 also includes https://github.com/sourmash-bio/sourmash/pull/3434, which changes the behavior of `Signature::name()` to return an `Option` if `name` is not set, rather than defaulting to either `filename()` or `md5sum()`, in that order. This caused a bug (see …

MRG: update to (prospective) sourmash r0.18.0

---

Cargo.lock
Cargo.toml

Changes and additions:
* MRG: switch to `importlib.metadata` from `pkg_resources` (into main) by @ctb in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/547
* MRG: add `--output-all-comparisons` to manysearch, multisearch, and pairwise by @ctb in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/544* MRG: update to (prospective) sourmash r0.18.0 by @ctb in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/548
* MRG: add capacity for skipmer sketching and search by @bluegenes in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/531
* MRG: integrate sketching utils from directsketch by @bluegenes in https://github.com/sourmash-bio/sourmash_plugin_branchwater/pull/516
Updates:
* Bump pyo3 from 0.22.6 to 0.23.1 by @dependabot in …

MRG: bump to version 0.9.12

---

pyproject.toml

MRG: add version to `pyproject.toml`

---

src/python/tests/test_sketch.py
src/utils/buildutils.rs

- Use needletail `parse_fastx_stdin` instead of `parse_fastx_reader`
- Add test for `stdin` to `singlesketch`
- fixes #572  
- Fix `singlesketch` tests that were checking 0 hashes (using scaled=1000 does not work for most small test fasta)

MRG: add tests for `stdin` input to `singlesketch` 

---

src/python/tests/test_sketch.py
src/utils/buildutils.rs

It turns out the manifest test were re-building the manifest from the sigs, and not testing the manifest in the zip file. This PR rectifies that and fixes the code for `n_hashes`.

MRG: test generated manifest 

---

doc/README.md
src/lib.rs
src/python/sourmash_plugin_branchwater/__init__.py
src/python/tests/test_sketch.py
src/singlesketch.rs

Fixes https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/535

MRG: support multiple input files for singlesketch

---

environment.yml
pyproject.toml
src/python/tests/test_sketch.py

=> Various tests now rely on skipmer functionality added in https://github.com/sourmash-bio/sourmash/pull/3446 and https://github.com/sourmash-bio/sourmash/pull/3457.

MRG: update to sourmash v4.8.13 (python package)

---

Cargo.lock
Cargo.toml
environment.yml
pyproject.toml

NOTE: have to wait for sourmash v4.8.13 conda-forge & bioconda packages to build before release.

MRG: bump plugin version to v0.9.13

---

pyproject.toml

MRG: remove ORCID from authors table in pyproject.toml

---

src/python/sourmash_plugin_branchwater/__init__.py

Updated documentation to reference the behavior of `--force` in do_manysketch to indicate this option allows "use of individual FASTA files in more than  _one_ sketch"

Documentation update: `manysketch --force` allows use of FASTA files in more than one sketch

---

Cargo.lock
Cargo.toml
environment.yml

- update rust to 1.75 in `Cargo.toml`
- also pin rust to  1.75 in `environment.yml` to make sure we're installing the pinned rust version for tests.
Actually, we were already installing 1.75 here! So we were on 1.75 for tests already: https://github.com/sourmash-bio/sourmash_plugin_branchwater/blob/main/.github/workflows/build-test.yml#L47C11-L47C38
This puts us out of sync with base sourmash (1.74), but it doesn't seem to present an issue here.
@ctb thoughts on pinning version in `environment.yml` vs in the `build-test.yml` workflow (or keeping both)?

upd rust to 1.75 for zip compatibility

---

src/manysearch.rs
src/manysearch_rocksdb.rs
src/python/tests/test_manysearch.py
src/utils/mod.rs

For a project, we'd like to know the fraction of each metagenome matched by the query. 
I propose adding two columns to `manysearch` results:
- `containment_target_in_query` -  the % of the unique metagenome content matching the query
- `f_weighted_target_in_query` - the % of weighted metagenome content matching the query
We were already calculating the first, just not reporting it. Getting the second (`f_weighted_target_in_query`) is straightforward if we're already calculating the abundance stats, I think: `abundance-weighted sum of intersected hashes` / `abundance-weighted sum of all metagenome hashes`. 
`manysearch` doesn't have a single number for the reverse abundance stat: instead we have `avg_abund`, `med_abund`, `std_abund` for the query. But that's because we're dividing by the …

MRG: report % of target matched by query
